### ISSUE TITLE
including map view in contacts

### ISSUE THREAD

**Issue by codecoda80** [Lapikud/lapikud.github.io#26]
The map is currently only on the Helpdesk page but it would make sense for it to be included under Contacts also

**Comment by marterki** [comment]
![kontakt](https://user-images.githubusercontent.com/9056088/46308216-c2102c80-c5c1-11e8-95d9-02116dae48b7.png)
Does this look too busy with the banner and all ? Position elsewhere ?

**Comment by artizirk** [comment]
imho it looks pretty good. 
Is this the commit that implements it? https://github.com/marterki/lapikud.github.io/commit/d35056c65dc1505975d03a9d02501b3d3cae501a

@Hermanio @TheAngryDuck @codecoda80  can you give also your opinion?

**Comment by artizirk** [comment]
I would recommend creating a seperate branch for this issue by
1. switching to that commit using command `git checkout d35056c65dc1505975d03a9d02501b3d3cae501a`
2. then creating a branch `git checkout -b issue26`
3. and pushing it to github `git push -u origin issue26`
4. then on github webpage you can select issue26 branch and create a pull request from that

**Comment by artizirk** [comment]
@releese you should also look over this

**Comment by releese** [comment]
![image](https://user-images.githubusercontent.com/28250826/46339288-0b509280-c63b-11e8-9a38-bb2089626f0d.png)
I would try adding the helpdesk banner to the right. Then it would look more unified in my opinion.

**Comment by artizirk** [comment]
you should then also unify the text style of helpdesk and lapikud contact info block

**Comment by marterki** [comment]
![desktop](https://user-images.githubusercontent.com/9056088/46344925-638f9080-c64b-11e8-812d-d6ae5aeb3df6.png)
![mobile](https://user-images.githubusercontent.com/9056088/46344926-64282700-c64b-11e8-98db-30bd5803adb0.png)
Hows this ?

**Comment by Hermanio** [comment]
Helpdesk banner should have a bit more white space at top and bottom on mobile, otherwise looks OK.

**Comment by marterki** [comment]
![mobile](https://user-images.githubusercontent.com/9056088/46399109-87aca980-c6ff-11e8-9344-b1d046660c71.png)
Both banner and map have more whitespace and map should wrap at the same time with the banner.
