### ISSUE TITLE
Create view for business people/future partners

### ISSUE THREAD

**Issue by Hermanio** [Lapikud/lapikud.github.io#4]
Contents: 

- Banner to encourage contacting us
- Work we have done as a carousel (easy to implement)

**Comment by Hermanio** [comment]
Initial basic version is complete. Content updates are in separate issue.

**Comment by artizirk** [comment]
I would remove the carousel and replace it with a simple top down list
It would be awesome if the content came from data yml files like in laphack

https://github.com/Lapikud/laphack.eu/blob/master/_data/mentors.yml
https://github.com/Lapikud/laphack.eu/blob/master/mentors.html

**Comment by Hermanio** [comment]
Latest revision has the completed work as a simple list that is populated from ourwork.yml data.
