### ISSUE TITLE
Update TTÜ logos to TalTech under "Koostööpartnerid"

### ISSUE THREAD

**Issue by releese** [Lapikud/lapikud.github.io#40]
[https://imgur.com/a/WUhmAC2](url)

**Comment by artizirk** [comment]
Kas svg vektor kujul taltech logo on kusagil olemas?

**Comment by releese** [comment]
Hetkel ei tundunud olevat. Saadan neile kirja tagasi, et saadaks SVG logod ka.

**Comment by TerjeRusska** [comment]
Kas vektor logo siiamaani vaja? LAPhacki drive-is .ai fail olemas

**Comment by artizirk** [comment]
oleks vist nice kui seal oleks svg

**Comment by psannus** [comment]
https://www.ttu.ee/ulikool/tutvustus/logo/

converted pdf to svg, seems good to go
[TalTech_IT_EST_gradient.zip](https://github.com/Lapikud/lapikud.github.io/files/4629109/TalTech_IT_EST_gradient.zip)

**Comment by psannus** [comment]
Fixed in these last commits.
