### ISSUE TITLE
Fix completion date of Tallinna Tehnikaülikooli Muuseumi eksponaadid

### ISSUE THREAD

**Issue by kuuseke1** [Lapikud/lapikud.github.io#50]
First entry (Tallinna Tehnikaülikooli Muuseumi eksponaadid) under https://www.lapikud.ee/ourwork says it will be completed in September 2018. Should be changed to whenever it was actually completed.

**Comment by psannus** [comment]
It was also completed in September 2018.

**Comment by psannus** [comment]
Fixed in commit https://github.com/Lapikud/lapikud.github.io/commit/c23a04857aa967d68b209f2d6dba3df1de1bd21e
