### ISSUE TITLE
Create mentors view + content generating scripts

### ISSUE THREAD

**Issue by Hermanio** [Lapikud/lapikud.github.io#6]
Mentors view contents:

- General description paragraph
- List of mentors and descriptions with contacting methods

Scripts should take the form data we get from mentors who agree to do the mentoring and generate HTML/Markdown for that section of the page. Form data could be formatted in CSV for example. 

Mentor images need to be compressed using imagemagick and then pushed into page assets.

**Comment by artizirk** [comment]
Laphack has some examples on how to do it

https://github.com/Lapikud/laphack.eu/blob/master/_data/team.yml
https://github.com/Lapikud/laphack.eu/blob/master/contact.html
https://github.com/Lapikud/laphack.eu/blob/master/conver_team_images.sh

**Comment by Hermanio** [comment]
First version of view implemented, waiting for mentors data and images to finish task.

**Comment by Hermanio** [comment]
Current version is good enough.
