### ISSUE TITLE
Magnus Teekivi was removed from senior members without being added to graduates

### ISSUE THREAD

**Issue by Teekivi** [Lapikud/lapikud.github.io#60]
I (Magnus Teekivi) was rightfully removed from senior members of Lapikud homepage in [a commit from August 2019](https://github.com/Lapikud/lapikud.github.io/commit/73ae7c331c3adf507e43e37947b0f558e9a1d6d9).

For me, the problem is that to this date, my name has not been added to the list of Lapikud graduates. But I actually am a graduate of Lapikud. :)

Maybe other (current or previous) members could have had similar same fate?

Could this get fixed?

Thanks in advance,
Magnus Teekivi,
Member of Lapikud from late 2015 to early 2019, graduate thereafter.

**Comment by MattiasVahtra** [comment]
Hey!

Added you to graduates where you belong :). Hopefully no one else has suffered the same fate.

All the best,
Mattias Vahtra
